# Generated by Django 5.1.2 on 2025-10-15 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_guestuser_eventregistration_appointmentrequest_and_more'),
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprogram',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Community organization managing this program', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_programs', to='accounts.communityprofile'),
        ),
        migrations.AlterField(
            model_name='healthprogram',
            name='partner_organizations',
            field=models.JSONField(blank=True, default=list, help_text='List of partner organization names'),
        ),
        migrations.AddIndex(
            model_name='healthprogram',
            index=models.Index(fields=['organization'], name='community_h_organiz_228c98_idx'),
        ),
    ]
