# Generated by Django 5.1.2 on 2025-10-15 23:58

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProgramType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(blank=True, max_length=200, null=True)),
                ('organization_type', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('organization_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('organization_address', models.TextField(blank=True, null=True)),
                ('orgnaization_logo', models.ImageField(blank=True, null=True, upload_to='orgnaization_logos/')),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(blank=True, choices=[('certificate', 'Certificate'), ('license', 'License'), ('other', 'Other')], max_length=100, null=True)),
                ('file', models.FileField(upload_to='organization_files/')),
                ('file_type', models.CharField(blank=True, max_length=10, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('TEXT', 'Text'), ('MULTIPLE CHOICE', 'Multiple Choice'), ('MULTIPLE SELECT', 'Multiple Select')])),
                ('question', models.CharField(max_length=240)),
                ('required', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=240)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponseAnswers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('response', 'question', 'date_created'),
            },
        ),
        migrations.CreateModel(
            name='SurveyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='communityprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='healthsurvey',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='healthsurvey',
            name='program',
        ),
        migrations.RemoveField(
            model_name='programreport',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='programreport',
            name='program',
        ),
        migrations.AlterModelOptions(
            name='surveyresponse',
            options={'ordering': ['-date_created']},
        ),
        migrations.RemoveIndex(
            model_name='surveyresponse',
            name='survey_resp_survey__ead8c2_idx',
        ),
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='submitted_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='updated_at',
            new_name='last_updated',
        ),
        migrations.RenameIndex(
            model_name='healthprogram',
            new_name='community_h_program_3bbe44_idx',
            old_name='community_h_program_5bbfb3_idx',
        ),
        migrations.RemoveField(
            model_name='healthprogram',
            name='program_type_custom',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='language_used',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='offline_id',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='respondent',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='respondent_age',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='respondent_gender',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='respondent_location',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='respondent_name',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='synced_at',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterModelTable(
            name='surveyresponse',
            table=None,
        ),
        migrations.AlterField(
            model_name='healthprogram',
            name='program_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_programs', to='communities.healthprogramtype'),
        ),
        migrations.AddField(
            model_name='organization',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthprogramtype',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='health_program_types', to='communities.organization'),
        ),
        migrations.AlterField(
            model_name='healthprogram',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Community organization managing this program', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_programs', to='communities.organization'),
        ),
        migrations.AddField(
            model_name='survey',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bulksurveyupload',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_uploads', to='communities.survey'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='communities.survey'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='communities.survey'),
        ),
        migrations.AddField(
            model_name='surveyquestionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='communities.surveyquestion'),
        ),
        migrations.AddField(
            model_name='surveyresponseanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='communities.surveyquestion'),
        ),
        migrations.AddField(
            model_name='surveyresponseanswers',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='communities.surveyresponse'),
        ),
        migrations.AddField(
            model_name='surveytype',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='survey_types', to='communities.organization'),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='communities.surveytype'),
        ),
        migrations.DeleteModel(
            name='ProgramReport',
        ),
        migrations.DeleteModel(
            name='CommunityProfile',
        ),
        migrations.DeleteModel(
            name='HealthSurvey',
        ),
    ]
