# Generated by Django 5.1.2 on 2025-10-15 01:32

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_healthprogram_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Since community_profiles table already exists (created by accounts app),
        # we just need to tell Django that this table now belongs to communities app
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CommunityProfile',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('organization_name', models.CharField(blank=True, max_length=200, null=True)),
                        ('organization_type', models.CharField(blank=True, max_length=100, null=True)),
                        ('volunteer_status', models.BooleanField(default=False)),
                        ('coordinator_level', models.CharField(blank=True, max_length=50, null=True)),
                        ('areas_of_focus', models.JSONField(blank=True, default=list)),
                        ('organization_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                        ('organization_email', models.EmailField(blank=True, max_length=254, null=True)),
                        ('organization_address', models.TextField(blank=True, null=True)),
                        ('active_programs', models.JSONField(blank=True, default=list)),
                        ('certifications', models.JSONField(blank=True, default=list)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_profile', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Community Profile',
                        'verbose_name_plural': 'Community Profiles',
                        'db_table': 'community_profiles',
                    },
                ),
            ],
            # No database operations needed since the table already exists
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='healthprogram',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Community organization managing this program', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_programs', to='communities.communityprofile'),
        ),
    ]
