# Generated by Django 5.1.2 on 2025-10-17 00:59

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_healthprogramtype_organization_organizationfiles_and_more'),
        ('patients', '0002_rename_home_address_patientprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date')], default='TEXT')),
                ('name', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterventionFieldOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterventionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('participant_id', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='The phone number of the participant', max_length=128, null=True, region=None)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterventionResponseValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramInterventionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='programintervention',
            options={'verbose_name': 'Program Intervention', 'verbose_name_plural': 'Program Interventions'},
        ),
        migrations.RemoveIndex(
            model_name='programintervention',
            name='program_int_program_7ae694_idx',
        ),
        migrations.RemoveIndex(
            model_name='programintervention',
            name='program_int_partici_d61c3d_idx',
        ),
        migrations.RenameField(
            model_name='programintervention',
            old_name='documented_at',
            new_name='created_at',
        ),
        migrations.RenameIndex(
            model_name='programintervention',
            new_name='program_int_interve_0716d2_idx',
            old_name='program_int_interve_5e5c70_idx',
        ),
        migrations.RemoveField(
            model_name='healthprogram',
            name='lead_organizer',
        ),
        migrations.RemoveField(
            model_name='healthprogram',
            name='lead_organizer_contact',
        ),
        migrations.RemoveField(
            model_name='healthprogram',
            name='team_members',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='description',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='documented_by',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='ehr_record_id',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='follow_up_date',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='follow_up_required',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='height',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='intervention_name',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='offline_id',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='participant_age',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='participant_gender',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='participant_id',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='participant_name',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='participant_phone',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='pulse',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='referral_facility',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='referral_needed',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='referral_notes',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='synced_to_ehr',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='test_results',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='treatment_given',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='vaccination_date',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='vaccine_administered',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='vaccine_batch_number',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='vaccine_dose_number',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='weight',
        ),
        migrations.AddField(
            model_name='organizationfiles',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='communities.organization'),
        ),
        migrations.AlterField(
            model_name='bulkinterventionupload',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bulksurveyupload',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='healthprogram',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='healthprogramtype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organizationfiles',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organizationfiles',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='programintervention',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='programintervention',
            name='program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intervention', to='communities.healthprogram'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='surveyquestionoption',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='surveyresponseanswers',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='surveytype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='interventionfield',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='communities.programintervention'),
        ),
        migrations.AddField(
            model_name='interventionfieldoption',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='communities.interventionfield'),
        ),
        migrations.AddField(
            model_name='interventionresponse',
            name='intervention',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervention_responses', to='communities.programintervention'),
        ),
        migrations.AddField(
            model_name='interventionresponse',
            name='patient_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervention_field_responses', to='patients.patientprofile'),
        ),
        migrations.AddField(
            model_name='interventionresponsevalue',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='communities.interventionfield'),
        ),
        migrations.AddField(
            model_name='interventionresponsevalue',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_values', to='communities.interventionresponse'),
        ),
        migrations.AddField(
            model_name='programinterventiontype',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='program_intervention_types', to='communities.organization'),
        ),
        migrations.AlterField(
            model_name='programintervention',
            name='intervention_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='communities.programinterventiontype'),
        ),
        migrations.AddIndex(
            model_name='programintervention',
            index=models.Index(fields=['program'], name='program_int_program_77a3e2_idx'),
        ),
    ]
