# Generated by Django 5.1.2 on 2025-11-08 01:17

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0002_organization_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("fullname", models.CharField(max_length=255)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name="interventionresponsevalue",
            old_name="participant",
            new_name="response",
        ),
        migrations.RemoveField(
            model_name="interventionresponse",
            name="participant_id",
        ),
        migrations.AddField(
            model_name="healthprogram",
            name="title_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="health_programs/title_images/"
            ),
        ),
        migrations.AlterField(
            model_name="healthprogram",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=18, max_digits=19, null=True
            ),
        ),
        migrations.AlterField(
            model_name="healthprogram",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=18, max_digits=19, null=True
            ),
        ),
        migrations.AlterField(
            model_name="interventionfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("BOOLEAN", "Boolean"),
                    ("NUMBER", "Number"),
                    ("SELECTION", "Selction"),
                    ("DATE", "Date"),
                ],
                default="TEXT",
            ),
        ),
        migrations.AddField(
            model_name="interventionresponse",
            name="participant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intervention_responses",
                to="communities.participant",
            ),
        ),
    ]
