# Generated by Django 5.1.2 on 2025-10-15 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_communityprofile_alter_healthprogram_organization'),
        ('facilities', '0002_facility_alter_facilityprofile_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programintervention',
            name='referral_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.facility'),
        ),
    ]
