# Generated by Django 5.1.2 on 2025-11-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0003_participant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="locumjob",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="surveyquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("BOOLEAN", "Boolean"),
                    ("NUMBER", "Number"),
                    ("SELECTION", "Selction"),
                    ("DATE", "Date"),
                ]
            ),
        ),
    ]
