# Generated by Django 5.1.2 on 2025-10-17 02:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_interventionfield_interventionfieldoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProgramPartners',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='health_program_partners/logos/')),
                ('url', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='healthprogram',
            name='equipment_list',
        ),
        migrations.RemoveField(
            model_name='healthprogram',
            name='interventions_planned',
        ),
        migrations.RemoveField(
            model_name='healthprogram',
            name='is_synced',
        ),
        migrations.RemoveField(
            model_name='healthprogram',
            name='locum_needs',
        ),
        migrations.RemoveField(
            model_name='healthprogram',
            name='offline_id',
        ),
        migrations.AlterField(
            model_name='healthprogram',
            name='funding_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='healthprogram',
            name='partner_organizations',
        ),
        migrations.CreateModel(
            name='LocumJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='locum_jobs/title_images/')),
                ('renumeration', models.DecimalField(decimal_places=2, max_digits=19)),
                ('renumeration_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locum_jobs', to='communities.organization')),
            ],
        ),
        migrations.CreateModel(
            name='HealthProgramLocumNeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locum_needs', to='communities.healthprogram')),
                ('locum_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locum_needs', to='communities.locumjob')),
            ],
        ),
        migrations.CreateModel(
            name='LocumJobRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ManyToManyField(blank=True, related_name='locum_job_roles', to='communities.organization')),
            ],
        ),
        migrations.AddField(
            model_name='locumjob',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locum_jobs', to='communities.locumjobrole'),
        ),
        migrations.AddField(
            model_name='healthprogram',
            name='partner_organizations',
            field=models.ManyToManyField(blank=True, related_name='health_programs_partners', to='communities.healthprogrampartners'),
        ),
    ]
