# Generated by Django 5.1.2 on 2025-10-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_alter_programintervention_referral_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprogram',
            name='equipment_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='healthprogram',
            name='equipment_needs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthprogram',
            name='locum_needs',
            field=models.JSONField(blank=True, default=list, help_text='List of required roles: {role, quantity, duration}'),
        ),
        migrations.DeleteModel(
            name='ProgramSchedule',
        ),
    ]
