# Generated by Django 5.1.2 on 2025-10-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_healthprogrampartners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
