# Generated by Django 5.1.2 on 2025-12-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0006_healthprogram_approval_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="banner",
            field=models.ImageField(
                blank=True, null=True, upload_to="organization_banners/"
            ),
        ),
    ]
