# Generated by Django 5.1.2 on 2026-01-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0008_alter_programintervention_program_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="locumjob",
            name="job_type",
            field=models.CharField(
                choices=[("volunteering", "Volunteering"), ("paid", "Paid")],
                default="paid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="locumjob",
            name="renumeration",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=19, null=True
            ),
        ),
        migrations.AlterField(
            model_name="locumjob",
            name="renumeration_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hourly", "Hourly"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
