# Generated by Django 6.0.4 on 2026-04-22 08:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_locumjob_job_type_alter_locumjob_renumeration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('template_type', models.CharField(choices=[('builtin', 'Built-in Design'), ('image_overlay', 'Image Overlay'), ('pdf_placeholder', 'PDF with Placeholders')], default='builtin', max_length=20)),
                ('builtin_style', models.CharField(blank=True, choices=[('classic', 'Classic'), ('professional', 'Professional'), ('modern', 'Modern'), ('elegant', 'Elegant')], default='classic', max_length=20)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='certificate_templates/backgrounds/')),
                ('pdf_template', models.FileField(blank=True, null=True, upload_to='certificate_templates/pdf/')),
                ('primary_color', models.CharField(default='#009EDB', max_length=7)),
                ('secondary_color', models.CharField(default='#00c7a6', max_length=7)),
                ('accent_color', models.CharField(default='#7733FF', max_length=7)),
                ('custom_logo', models.ImageField(blank=True, null=True, upload_to='certificate_templates/logos/')),
                ('header_text', models.CharField(default='Certificate of Participation', max_length=255)),
                ('body_text', models.TextField(default='This is to certify that {{participant_name}} has successfully participated in {{program_name}} organized by {{organization_name}} from {{start_date}} to {{end_date}}.')),
                ('footer_text', models.CharField(blank=True, default='', max_length=255)),
                ('signatory_name', models.CharField(blank=True, default='', max_length=255)),
                ('signatory_title', models.CharField(blank=True, default='', max_length=255)),
                ('signatory_signature', models.ImageField(blank=True, null=True, upload_to='certificate_templates/signatures/')),
                ('show_qr_code', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='communities.organization')),
            ],
            options={
                'verbose_name': 'Certificate Template',
                'verbose_name_plural': 'Certificate Templates',
                'db_table': 'certificate_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssuedCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='issued_certificates/')),
                ('verification_hash', models.CharField(max_length=64, unique=True)),
                ('verification_code', models.CharField(max_length=12, unique=True)),
                ('is_emailed', models.BooleanField(default=False)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('invitation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate', to='communities.healthprograminvitation')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_issued', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to='communities.healthprogram')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='communities.certificatetemplate')),
            ],
            options={
                'verbose_name': 'Issued Certificate',
                'verbose_name_plural': 'Issued Certificates',
                'db_table': 'issued_certificates',
                'ordering': ['-issued_at'],
            },
        ),
    ]
