# Generated by Django 6.0.4 on 2026-06-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0012_staff_accepted_at_staff_invited_at_staff_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locumjob',
            name='currency',
            field=models.CharField(blank=True, default='GHS', max_length=8),
        ),
    ]
