# Generated by Django 6.0.4 on 2026-06-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0013_locumjob_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprogram',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20),
        ),
    ]
