# Generated by Django 6.0.4 on 2026-06-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0014_alter_healthprogram_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interventionfield',
            options={'ordering': ['order', 'date_created']},
        ),
        migrations.AddField(
            model_name='interventionfield',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
