# Generated by Django 6.0.4 on 2026-06-25 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0016_programintervention_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprograminvitation',
            name='locum_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_invitations', to='communities.locumjobapplication'),
        ),
        migrations.AddField(
            model_name='healthprograminvitation',
            name='source',
            field=models.CharField(choices=[('INVITE', 'Invite'), ('LOCUM', 'Locum')], default='INVITE', max_length=10),
        ),
    ]
