# Generated by Django 6.0.4 on 2026-08-02 23:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0017_healthprograminvitation_locum_application_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_platform_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Intervention Template',
                'verbose_name_plural': 'Intervention Templates',
                'db_table': 'intervention_templates',
                'ordering': ['-is_platform_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InterventionTemplateField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('BOOLEAN', 'Boolean'), ('NUMBER', 'Number'), ('SELECTION', 'Selction'), ('DATE', 'Date')], default='TEXT', max_length=20)),
                ('section', models.CharField(choices=[('PARTICIPANT', 'Participant Information'), ('VITALS', 'Vitals'), ('INTERVENTION', 'Intervention-Specific')], default='INTERVENTION', max_length=20)),
                ('field_key', models.CharField(blank=True, choices=[('height', 'Height (cm)'), ('weight', 'Weight (kg)'), ('bmi', 'Body Mass Index'), ('blood_pressure', 'Blood Pressure'), ('temperature', 'Temperature (°C)'), ('pulse', 'Pulse (bpm)'), ('respiratory_rate', 'Respiratory Rate'), ('blood_sugar', 'Blood Sugar'), ('oxygen_saturation', 'Oxygen Saturation (%)')], max_length=32, null=True)),
                ('is_computed', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('options', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'intervention_template_fields',
                'ordering': ['section', 'order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='interventionfield',
            options={'ordering': ['section', 'order', 'date_created']},
        ),
        migrations.AddField(
            model_name='interventionfield',
            name='field_key',
            field=models.CharField(blank=True, choices=[('height', 'Height (cm)'), ('weight', 'Weight (kg)'), ('bmi', 'Body Mass Index'), ('blood_pressure', 'Blood Pressure'), ('temperature', 'Temperature (°C)'), ('pulse', 'Pulse (bpm)'), ('respiratory_rate', 'Respiratory Rate'), ('blood_sugar', 'Blood Sugar'), ('oxygen_saturation', 'Oxygen Saturation (%)')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='interventionfield',
            name='is_computed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interventionfield',
            name='section',
            field=models.CharField(choices=[('PARTICIPANT', 'Participant Information'), ('VITALS', 'Vitals'), ('INTERVENTION', 'Intervention-Specific')], db_index=True, default='INTERVENTION', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='participant_code_prefix',
            field=models.CharField(blank=True, help_text="Prefix used for participant IDs, e.g. 'SJ' → SJ001.", max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Stated age at registration; ignored when date_of_birth is set.', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='location',
            field=models.CharField(blank=True, help_text='Community, town or district the participant came from.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='communities.organization'),
        ),
        migrations.AddField(
            model_name='participant',
            name='participant_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('undisclosed', 'Prefer not to say')], max_length=12, null=True),
        ),
        migrations.AddIndex(
            model_name='interventionfield',
            index=models.Index(fields=['intervention', 'section', 'order'], name='communities_interve_aefaf4_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['organization', 'date_created'], name='communities_organiz_d4bbc9_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['phone_number'], name='communities_phone_n_c141ed_idx'),
        ),
        migrations.AddField(
            model_name='interventiontemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_intervention_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interventiontemplate',
            name='intervention_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='communities.programinterventiontype'),
        ),
        migrations.AddField(
            model_name='interventiontemplate',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Null for platform-wide templates available to every organisation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intervention_templates', to='communities.organization'),
        ),
        migrations.AddField(
            model_name='interventiontemplatefield',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='communities.interventiontemplate'),
        ),
        migrations.AddConstraint(
            model_name='interventiontemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_template_name_per_org'),
        ),
    ]
