# Generated by Django 6.0.4 on 2026-08-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0018_interventiontemplate_interventiontemplatefield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locumjob',
            name='open_to_non_professionals',
            field=models.BooleanField(default=False, help_text='Allow applicants without a health-professional profile. Only meaningful for volunteering roles.'),
        ),
        migrations.AddField(
            model_name='locumjobapplication',
            name='applicant_type',
            field=models.CharField(choices=[('health_professional', 'Health Professional'), ('student', 'Student / In training'), ('non_professional', 'Non-Health Professional')], default='health_professional', max_length=32),
        ),
        migrations.AddField(
            model_name='locumjobapplication',
            name='background',
            field=models.TextField(blank=True, help_text='Relevant skills or background, for non-professional applicants.'),
        ),
    ]
