# Generated by Django 6.0.4 on 2026-08-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0019_locumjob_open_to_non_professionals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_clinical',
            field=models.BooleanField(default=False, help_text='Whether this member is a qualified health professional. Non-clinical members are never displayed as medical personnel.'),
        ),
        migrations.AddField(
            model_name='staff',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
