# Generated by Django 6.0.4 on 2026-08-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0020_staff_is_clinical_staff_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionresponse',
            name='entry_mode',
            field=models.CharField(choices=[('live', 'Captured live'), ('transcribed', 'Transcribed from paper'), ('imported', 'Bulk imported')], default='live', max_length=16),
        ),
        migrations.AddField(
            model_name='interventionresponse',
            name='recorded_at',
            field=models.DateTimeField(blank=True, help_text='When the data was collected. Defaults to the entry time.', null=True),
        ),
    ]
