# Generated by Django 6.0.4 on 2026-08-03 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0021_interventionresponse_entry_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionresponse',
            name='client_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='Client-generated id used to de-duplicate offline submissions.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='interventionresponse',
            name='synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record arrived from an offline queue.', null=True),
        ),
        migrations.AddField(
            model_name='interventionresponsevalue',
            name='recorded_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionresponsevalue',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_response_values', to=settings.AUTH_USER_MODEL),
        ),
    ]
