# Generated by Django 6.0.4 on 2026-08-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0022_interventionresponse_client_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programintervention',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
