# Generated by Django 6.0.4 on 2026-08-12 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0024_seed_intervention_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='participant_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='communities.healthprogram'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['program', 'participant_number'], name='communities_program_7a86d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('program', 'participant_number'), name='uniq_participant_number_per_program'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(condition=models.Q(('participant_number__gte', 1)), name='participant_number_is_positive'),
        ),
    ]
