# Generated by Django 5.1.2 on 2025-10-25 23:48

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pharmacy_name', models.CharField(max_length=200)),
                ('pharmacy_license', models.CharField(max_length=100, unique=True)),
                ('pharmacy_type', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('services_offered', models.JSONField(blank=True, default=list)),
                ('delivery_available', models.BooleanField(default=False)),
                ('delivery_radius', models.IntegerField(default=0)),
                ('operating_hours', models.JSONField(blank=True, default=dict)),
                ('pharmacist_license', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_count', models.IntegerField(default=1)),
                ('payment_methods', models.JSONField(blank=True, default=list)),
                ('insurance_accepted', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pharmacy Profile',
                'verbose_name_plural': 'Pharmacy Profiles',
                'db_table': 'pharmacy_profiles',
            },
        ),
    ]
