# Generated by Django 5.1.2 on 2026-01-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pharmacyprofile",
            name="insurance_accepted",
        ),
        migrations.RemoveField(
            model_name="pharmacyprofile",
            name="operating_hours",
        ),
        migrations.RemoveField(
            model_name="pharmacyprofile",
            name="payment_methods",
        ),
        migrations.RemoveField(
            model_name="pharmacyprofile",
            name="pharmacy_type",
        ),
        migrations.RemoveField(
            model_name="pharmacyprofile",
            name="services_offered",
        ),
        migrations.RemoveField(
            model_name="pharmacyprofile",
            name="staff_count",
        ),
        migrations.AddField(
            model_name="pharmacyprofile",
            name="license_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pharmacyprofile",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="pharmacyprofile",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
