# Generated by Django 5.1.2 on 2026-01-25 03:41

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0003_drugcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drugcategory",
            name="description",
        ),
        migrations.AddField(
            model_name="drugcategory",
            name="pharmacy",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drug_categories",
                to="pharmacies.pharmacyprofile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="drugcategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "base_unit",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablet"),
                            ("capsule", "Capsule"),
                            ("blister", "Blister pack"),
                            ("box", "Box"),
                            ("bottle", "Bottle"),
                            ("vial", "Vial"),
                            ("ampoule", "Ampoule"),
                            ("tube", "Tube"),
                            ("sachet", "Sachet"),
                            ("inhaler", "Inhaler"),
                            ("syringe", "Prefilled syringe"),
                            ("pen", "Injection pen"),
                        ],
                        help_text="Smallest measurable unit (e.g. tablet, ml)",
                        max_length=20,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price per base unit", max_digits=10
                    ),
                ),
                ("low_stock_threshold", models.IntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drugs",
                        to="pharmacies.drugcategory",
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drugs",
                        to="pharmacies.pharmacyprofile",
                    ),
                ),
            ],
            options={
                "db_table": "drugs",
            },
        ),
        migrations.CreateModel(
            name="DrugSupplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="pharmacies.pharmacyprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Drug Supplier",
                "verbose_name_plural": "Drug Suppliers",
                "db_table": "drug_suppliers",
            },
        ),
        migrations.CreateModel(
            name="DrugBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("batch_number", models.CharField(max_length=100)),
                ("expiry_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="pharmacies.drug",
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="pharmacies.pharmacyprofile",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="pharmacies.drugsupplier",
                    ),
                ),
            ],
            options={
                "db_table": "drug_batches",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Positive for stock-in, negative for stock-out"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("restock", "Restock"),
                            ("sale", "Sale"),
                            ("return", "Return"),
                            ("adjustment", "Adjustment"),
                            ("expired", "Expired"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="pharmacies.drugbatch",
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="pharmacies.drug",
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="pharmacies.pharmacyprofile",
                    ),
                ),
            ],
            options={
                "db_table": "stock_movements",
            },
        ),
        migrations.AddIndex(
            model_name="drug",
            index=models.Index(
                fields=["pharmacy", "name"], name="drugs_pharmac_14988d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="drug",
            unique_together={("pharmacy", "name")},
        ),
        migrations.AddIndex(
            model_name="drugbatch",
            index=models.Index(
                fields=["expiry_date"], name="drug_batche_expiry__550081_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="drugbatch",
            unique_together={("drug", "batch_number")},
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["drug", "created_at"], name="stock_movem_drug_id_c06334_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["batch"], name="stock_movem_batch_i_3b9bea_idx"),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity", 0), _negated=True),
                name="quantity_not_zero",
            ),
        ),
    ]
