# Generated by Django 5.1.2 on 2026-01-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0004_remove_drugcategory_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="drugs/"),
        ),
        migrations.AddField(
            model_name="pharmacyprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
