# Generated by Django 5.1.2 on 2026-01-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0005_drug_image_pharmacyprofile_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="drugsupplier",
            name="contact_person",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
