# Generated by Django 5.1.2 on 2026-03-01 03:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_address"),
        (
            "pharmacies",
            "0007_callbackdata_order_orderitem_payment_paymentmethod_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PharmacyOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("ready", "Ready for Pickup"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pharmacy Order",
                "verbose_name_plural": "Pharmacy Orders",
                "db_table": "pharmacy_orders",
            },
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_pharmac_c2e821_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_prescri_37d9cc_idx",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_notes",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_phone",
        ),
        migrations.RemoveField(
            model_name="order",
            name="pharmacy",
        ),
        migrations.RemoveField(
            model_name="order",
            name="prescription_code",
        ),
        migrations.RemoveField(
            model_name="order",
            name="requires_delivery",
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="accounts.address",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[("delivery", "Delivery"), ("pickup", "Pickup")],
                default="pickup",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pharmacyorder",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pharmacy_orders",
                to="pharmacies.order",
            ),
        ),
        migrations.AddField(
            model_name="pharmacyorder",
            name="pharmacy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="pharmacies.pharmacyprofile",
            ),
        ),
    ]
