# Generated by Django 5.1.2 on 2026-03-09 03:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0009_alter_order_status_alter_pharmacyorder_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("settlement_date", models.DateField()),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("paid", "Paid")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="pharmacies.pharmacyprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Settlement",
                "verbose_name_plural": "Settlements",
                "db_table": "settlements",
                "ordering": ["-settlement_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SettlementOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_entries",
                        to="pharmacies.order",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_orders",
                        to="pharmacies.settlement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Settlement Order",
                "verbose_name_plural": "Settlement Orders",
                "db_table": "settlement_orders",
            },
        ),
        migrations.AddIndex(
            model_name="settlement",
            index=models.Index(
                fields=["pharmacy", "status"], name="settlements_pharmac_521df8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="settlement",
            index=models.Index(
                fields=["pharmacy", "settlement_date"],
                name="settlements_pharmac_2e1934_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="settlement",
            unique_together={("pharmacy", "settlement_date")},
        ),
        migrations.AddIndex(
            model_name="settlementorder",
            index=models.Index(
                fields=["settlement"], name="settlement__settlem_b94f9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="settlementorder",
            index=models.Index(fields=["order"], name="settlement__order_i_770810_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="settlementorder",
            unique_together={("settlement", "order")},
        ),
    ]
