# Generated by Django 6.0.4 on 2026-06-03 11:23

from django.db import migrations, models


DEFAULT_DELIVERY_RADIUS_KM = 10


def set_standard_radius(apps, schema_editor):
    """Bump pharmacies still on the old meaningless 0 default to the standard radius."""
    PharmacyProfile = apps.get_model('pharmacies', 'PharmacyProfile')
    PharmacyProfile.objects.filter(delivery_radius=0).update(
        delivery_radius=DEFAULT_DELIVERY_RADIUS_KM
    )


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0010_settlement_settlementorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='delivery_radius',
            field=models.IntegerField(default=10, help_text='Maximum delivery distance in km from the pharmacy.'),
        ),
        migrations.RunPython(set_standard_radius, migrations.RunPython.noop),
    ]
