# Generated by Django 6.0.4 on 2026-06-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0011_alter_pharmacyprofile_delivery_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='access_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
