# Generated by Django 6.0.4 on 2026-06-03 12:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0012_payment_access_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('transfer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='pharmacies.paymentmethod')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='pharmacies.pharmacyprofile')),
            ],
            options={
                'verbose_name': 'Settlement Payout',
                'verbose_name_plural': 'Settlement Payouts',
                'db_table': 'settlement_payouts',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='settlement',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='pharmacies.settlementpayout'),
        ),
        migrations.AddIndex(
            model_name='settlementpayout',
            index=models.Index(fields=['pharmacy', 'status'], name='settlement__pharmac_2e29c4_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementpayout',
            index=models.Index(fields=['reference'], name='settlement__referen_6cf6c1_idx'),
        ),
    ]
