# Generated by Django 6.0.4 on 2026-09-23 00:34

import django.db.models.deletion
from django.db import migrations, models


# Tech report 18.08.2026, item 2.2: "set some sample drug categories that
# exist as default in the system that users can choose, and/or add their own".
# A category with no pharmacy is a system default. Names are matched
# case-insensitively so a pharmacy's own "Antibiotics" is kept, not doubled.
DEFAULT_CATEGORIES = [
    "Analgesics",
    "Antibiotics",
    "Antimalarials",
    "Antihypertensives",
    "Antidiabetics",
    "Antihistamines",
    "Cough & Cold",
    "Gastrointestinal",
    "Dermatological",
    "Vitamins & Supplements",
    "Family Planning",
    "First Aid & Wound Care",
    "Eye & Ear Care",
    "Medical Devices",
]


def seed_defaults(apps, schema_editor):
    DrugCategory = apps.get_model("pharmacies", "DrugCategory")
    existing = {name.lower() for name in DrugCategory.objects.values_list("name", flat=True)}
    DrugCategory.objects.bulk_create(
        [DrugCategory(name=name, pharmacy=None) for name in DEFAULT_CATEGORIES if name.lower() not in existing]
    )


def remove_defaults(apps, schema_editor):
    DrugCategory = apps.get_model("pharmacies", "DrugCategory")
    # Only defaults that no drug uses can go; PROTECT stops the rest.
    DrugCategory.objects.filter(pharmacy__isnull=True, drugs__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0013_settlementpayout_settlement_payout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugcategory',
            name='pharmacy',
            field=models.ForeignKey(blank=True, help_text='Empty for a system default category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_categories', to='pharmacies.pharmacyprofile'),
        ),
        migrations.RunPython(seed_defaults, remove_defaults),
    ]
