# Generated by Django 5.1.2 on 2025-10-15 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_remove_partnerprofile_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Table already exists, just transfer ownership from accounts to facilities
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='FacilityProfile',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                        ('department', models.CharField(blank=True, max_length=100, null=True)),
                        ('position', models.CharField(blank=True, max_length=100, null=True)),
                        ('employment_type', models.CharField(blank=True, max_length=50, null=True)),
                        ('hire_date', models.DateField(blank=True, null=True)),
                        ('shift_schedule', models.JSONField(blank=True, default=dict)),
                        ('working_hours', models.JSONField(blank=True, default=dict)),
                        ('can_prescribe', models.BooleanField(default=False)),
                        ('can_access_patient_data', models.BooleanField(default=True)),
                        ('can_manage_inventory', models.BooleanField(default=False)),
                        ('can_schedule_appointments', models.BooleanField(default=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='accounts.facility')),
                        ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facility_profile', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Facility Profile',
                        'verbose_name_plural': 'Facility Profiles',
                        'db_table': 'facility_profiles',
                    },
                ),
            ],
            database_operations=[],  # No actual DB changes needed
        ),
    ]
