# Generated by Django 5.1.2 on 2025-10-15 01:59

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Facility',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=200)),
                        ('facility_code', models.CharField(max_length=50, unique=True)),
                        ('facility_type', models.CharField(max_length=100)),
                        ('address', models.TextField()),
                        ('district', models.CharField(max_length=100)),
                        ('region', models.CharField(max_length=100)),
                        ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                        ('email', models.EmailField(blank=True, max_length=254, null=True)),
                        ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                        ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                        ('is_active', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'Facility',
                        'verbose_name_plural': 'Facilities',
                        'db_table': 'facilities',
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='facilityprofile',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='facilities.facility'),
        ),
    ]
