# Generated by Django 5.1.2 on 2026-03-10 00:53

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0002_facility_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Locum",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "profession",
                    models.CharField(
                        choices=[
                            ("doctor", "Doctor"),
                            ("nurse", "Nurse"),
                            ("midwife", "Midwife"),
                            ("pharmacist", "Pharmacist"),
                            ("lab_technician", "Lab Technician"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "license_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                ("is_available", models.BooleanField(default=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locum_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "locums",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FacilityStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "profession",
                    models.CharField(
                        choices=[
                            ("doctor", "Doctor"),
                            ("nurse", "Nurse"),
                            ("midwife", "Midwife"),
                            ("pharmacist", "Pharmacist"),
                            ("lab_technician", "Lab Technician"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("employee_id", models.CharField(blank=True, max_length=50, null=True)),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="facilities.facility",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facility_staff",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "facility_staff",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["facility", "is_active"],
                        name="facility_st_facilit_0f5750_idx",
                    ),
                    models.Index(
                        fields=["facility", "profession"],
                        name="facility_st_facilit_92a96e_idx",
                    ),
                ],
            },
        ),
    ]
