# Generated by Django 5.1.2 on 2026-03-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_locum_facilitystaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='facility_code',
        ),
    ]
