# Generated by Django 5.1.2 on 2026-03-14 22:23

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0004_remove_facility_facility_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facilityprofile",
            name="facility",
        ),
        migrations.AlterField(
            model_name="facilitystaff",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_members",
                to="facilities.facilityprofile",
            ),
        ),
        migrations.AlterModelOptions(
            name="facilityprofile",
            options={"verbose_name": "Facility", "verbose_name_plural": "Facilities"},
        ),
        migrations.RenameField(
            model_name="facilityprofile",
            old_name="can_access_patient_data",
            new_name="is_active",
        ),
        migrations.RenameField(
            model_name="facilityprofile",
            old_name="employee_id",
            new_name="latitude",
        ),
        migrations.RenameField(
            model_name="facilityprofile",
            old_name="employment_type",
            new_name="longitude",
        ),
        migrations.RemoveField(
            model_name="facilityprofile",
            name="can_manage_inventory",
        ),
        migrations.RemoveField(
            model_name="facilityprofile",
            name="can_prescribe",
        ),
        migrations.RemoveField(
            model_name="facilityprofile",
            name="can_schedule_appointments",
        ),
        migrations.RemoveField(
            model_name="facilityprofile",
            name="department",
        ),
        migrations.RemoveField(
            model_name="facilityprofile",
            name="hire_date",
        ),
        migrations.RemoveField(
            model_name="facilityprofile",
            name="position",
        ),
        migrations.RemoveField(
            model_name="facilityprofile",
            name="shift_schedule",
        ),
        migrations.RemoveField(
            model_name="facilityprofile",
            name="supervisor",
        ),
        migrations.RemoveField(
            model_name="facilityprofile",
            name="working_hours",
        ),
        migrations.AddField(
            model_name="facilityprofile",
            name="address",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facilityprofile",
            name="district",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facilityprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="facilityprofile",
            name="facility_type",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facilityprofile",
            name="name",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facilityprofile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="facilityprofile",
            name="region",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facilityprofile",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name="facilityprofile",
            table="facilities",
        ),
        migrations.DeleteModel(
            name="Facility",
        ),
    ]
