# Generated by Django 6.0.4 on 2026-04-18 14:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_remove_facilityprofile_facility_and_more'),
        ('patients', '0008_facilitypatientaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityprofile',
            name='ghs_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facilityprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='facilities/logos/'),
        ),
        migrations.AddField(
            model_name='facilityprofile',
            name='nhis_accreditation_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facilityprofile',
            name='operating_hours',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FacilityAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_type', models.CharField(choices=[('IN_PERSON', 'In Person'), ('TELEHEALTH', 'Telehealth')], default='IN_PERSON', max_length=20)),
                ('consultation_type', models.CharField(choices=[('general', 'General Consultation'), ('follow_up', 'Follow-Up'), ('emergency', 'Emergency'), ('antenatal', 'Antenatal'), ('vaccination', 'Vaccination'), ('lab_test', 'Lab Test'), ('specialist', 'Specialist'), ('other', 'Other')], default='general', max_length=30)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show'), ('RESCHEDULED', 'Rescheduled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='facilities.facilityprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_appointments', to='patients.patientprofile')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='facilities.facilitystaff')),
            ],
            options={
                'db_table': 'facility_appointments',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=200)),
                ('test_category', models.CharField(choices=[('haematology', 'Haematology'), ('biochemistry', 'Biochemistry'), ('microbiology', 'Microbiology'), ('parasitology', 'Parasitology'), ('radiology', 'Radiology'), ('immunology', 'Immunology'), ('histopathology', 'Histopathology'), ('other', 'Other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sample_collected', 'Sample Collected'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('result', models.TextField(blank=True, null=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='lab_results/')),
                ('reference_range', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('resulted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='facilities.facilityprofile')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_lab_tests', to='facilities.facilitystaff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='patients.patientprofile')),
                ('visitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='patients.visitation')),
            ],
            options={
                'db_table': 'facility_lab_tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=200)),
                ('profession', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('midwife', 'Midwife'), ('pharmacist', 'Pharmacist'), ('lab_technician', 'Lab Technician'), ('other', 'Other')], max_length=40)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_invitations', to='facilities.facilityprofile')),
            ],
            options={
                'db_table': 'facility_staff_invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ward_type', models.CharField(choices=[('general', 'General'), ('icu', 'ICU'), ('maternity', 'Maternity'), ('pediatric', 'Pediatric'), ('surgical', 'Surgical'), ('emergency', 'Emergency'), ('isolation', 'Isolation'), ('psychiatric', 'Psychiatric'), ('other', 'Other')], default='general', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='facilities.facilityprofile')),
            ],
            options={
                'db_table': 'facility_wards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('admitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_assignments', to='patients.patientprofile')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='facilities.ward')),
            ],
            options={
                'db_table': 'facility_beds',
                'ordering': ['bed_number'],
                'unique_together': {('ward', 'bed_number')},
            },
        ),
    ]
