# Generated by Django 5.1.2 on 2025-10-15 01:47

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
            name='PartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_type', models.CharField(max_length=100)),
                ('organization_size', models.CharField(blank=True, max_length=50, null=True)),
                ('organization_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('organization_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('organization_address', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('partnership_type', models.CharField(max_length=100)),
                ('partnership_status', models.CharField(default='active', max_length=50)),
                ('partnership_start_date', models.DateField(blank=True, null=True)),
                ('partnership_end_date', models.DateField(blank=True, null=True)),
                ('api_access_level', models.CharField(default='basic', max_length=50)),
                ('can_access_analytics', models.BooleanField(default=False)),
                ('can_manage_subsidies', models.BooleanField(default=False)),
                ('can_view_patient_data', models.BooleanField(default=False)),
                ('contact_person_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_person_title', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
                    options={
                        'verbose_name': 'Partner Profile',
                        'verbose_name_plural': 'Partner Profiles',
                        'db_table': 'partner_profiles',
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
