# Generated by Django 6.0.4 on 2026-04-18 21:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_locumjob_job_type_alter_locumjob_renumeration_and_more'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerprofile',
            name='api_access_level',
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partner_logos/'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='can_access_analytics',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='can_manage_subsidies',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='organization_type',
            field=models.CharField(choices=[('ngo', 'NGO'), ('government', 'Government'), ('corporate', 'Corporate'), ('research', 'Research Institution'), ('foundation', 'Foundation'), ('international', 'International Organisation'), ('other', 'Other')], default='ngo', max_length=50),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='partnership_type',
            field=models.CharField(choices=[('funding', 'Funding'), ('technical', 'Technical'), ('service_provider', 'Service Provider'), ('research', 'Research'), ('advocacy', 'Advocacy')], default='funding', max_length=50),
        ),
        migrations.CreateModel(
            name='ProgramPartnershipRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('message', models.TextField(help_text='Why the partner wants to monitor this program')),
                ('report_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_requests', to='partners.partnerprofile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_requests', to='communities.healthprogram')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_partner_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'program_partnership_requests',
                'ordering': ['-created_at'],
                'unique_together': {('partner', 'program')},
            },
        ),
        migrations.CreateModel(
            name='ProgramMonitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_monitors', to='partners.partnerprofile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_monitors', to='communities.healthprogram')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitor', to='partners.programpartnershiprequest')),
            ],
            options={
                'db_table': 'program_monitors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('subsidy_type', models.CharField(choices=[('free_consultation', 'Free Consultation'), ('medication_discount', 'Medication Discount'), ('program_funding', 'Program Funding'), ('other', 'Other')], default='free_consultation', max_length=50)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=14)),
                ('budget_used', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target', models.TextField(help_text="Who this subsidy targets, e.g. 'Rural patients in Tamale'")),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('exhausted', 'Exhausted'), ('expired', 'Expired')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidies', to='partners.partnerprofile')),
            ],
            options={
                'db_table': 'partner_subsidies',
                'ordering': ['-created_at'],
            },
        ),
    ]
