# Generated by Django 6.0.4 on 2026-04-19 00:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_locumjob_job_type_alter_locumjob_renumeration_and_more'),
        ('partners', '0002_extend_partner_profile_add_subsidy_monitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPartnerInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('report_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_invitations', to='communities.organization')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_invitations', to='partners.partnerprofile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_partner_invitations', to='communities.healthprogram')),
            ],
            options={
                'db_table': 'organization_partner_invitations',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'partner', 'program')},
            },
        ),
    ]
