# Generated by Django 6.0.4 on 2026-04-19 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_add_organization_partner_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmonitor',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor', to='partners.programpartnershiprequest'),
        ),
    ]
