# Generated by Django 6.0.4 on 2026-04-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_locumjob_job_type_alter_locumjob_renumeration_and_more'),
        ('partners', '0004_make_program_monitor_request_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpartnershiprequest',
            name='direction',
            field=models.CharField(choices=[('partner_initiated', 'Partner Initiated'), ('org_initiated', 'Organisation Initiated')], default='partner_initiated', max_length=30),
        ),
        migrations.AlterField(
            model_name='programmonitor',
            name='report_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='programpartnershiprequest',
            name='message',
            field=models.TextField(blank=True, help_text='Why the partner wants to monitor this program'),
        ),
        migrations.AlterField(
            model_name='programpartnershiprequest',
            name='report_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='programmonitor',
            unique_together={('partner', 'program')},
        ),
        migrations.DeleteModel(
            name='OrganizationPartnerInvitation',
        ),
    ]
