# Generated by Django 6.0.4 on 2026-04-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_unify_partnership_requests_drop_org_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidy',
            name='subsidy_type',
            field=models.CharField(choices=[('cash_grant', 'Cash Grant'), ('free_consultation', 'Free Consultation'), ('medication_discount', 'Medication Discount'), ('program_funding', 'Program Funding'), ('other', 'Other')], default='free_consultation', max_length=50),
        ),
    ]
