# Generated by Django 5.1.2 on 2025-12-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="encrypted_content",
        ),
        migrations.AddField(
            model_name="message",
            name="content",
            field=models.TextField(default=1, help_text="Message content"),
            preserve_default=False,
        ),
    ]
