# Generated by Django 6.0.4 on 2026-08-02 23:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_aichatsession_user_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAbuseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('prompt_injection', 'Prompt Injection Attempt'), ('off_topic', 'Off-Topic Response'), ('quota_exceeded', 'Free Quota Exceeded')], default='prompt_injection', max_length=32)),
                ('prompt', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('matched_patterns', models.JSONField(blank=True, default=list)),
                ('strikes', models.IntegerField(default=0, help_text='Consecutive flagged prompts from this client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_abuse_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Abuse Event',
                'verbose_name_plural': 'AI Abuse Events',
                'db_table': 'ai_abuse_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='ai_abuse_ev_event_t_8c1a1c_idx'), models.Index(fields=['ip_address', 'created_at'], name='ai_abuse_ev_ip_addr_caa305_idx')],
            },
        ),
    ]
