# Generated by Django 5.1.2 on 2025-10-25 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='authenticationaudit',
            index=models.Index(fields=['user', 'timestamp'], name='authenticat_user_id_a5b418_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationaudit',
            index=models.Index(fields=['action', 'timestamp'], name='authenticat_action_0f1b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationaudit',
            index=models.Index(fields=['platform', 'timestamp'], name='authenticat_platfor_1142b8_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationaudit',
            index=models.Index(fields=['ip_address', 'timestamp'], name='authenticat_ip_addr_fc46ca_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccesslog',
            index=models.Index(fields=['user', 'timestamp'], name='data_access_user_id_0233e0_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccesslog',
            index=models.Index(fields=['data_type', 'timestamp'], name='data_access_data_ty_7fecbd_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccesslog',
            index=models.Index(fields=['platform', 'timestamp'], name='data_access_platfor_8c2e1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mfadevice',
            unique_together={('user', 'device_id')},
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role', 'facility')},
        ),
    ]
