# Generated by Django 5.1.2 on 2025-10-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20251015_0002'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mfadevice',
            name='unique_user_device',
        ),
        migrations.RemoveConstraint(
            model_name='role',
            name='unique_role_per_platform',
        ),
        migrations.RemoveConstraint(
            model_name='userrole',
            name='unique_user_role_facility',
        ),
        migrations.RenameIndex(
            model_name='authenticationaudit',
            new_name='authenticat_user_id_a5b418_idx',
            old_name='auth_audit_user_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='authenticationaudit',
            new_name='authenticat_action_0f1b2a_idx',
            old_name='auth_audit_action_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='authenticationaudit',
            new_name='authenticat_platfor_1142b8_idx',
            old_name='auth_audit_platform_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='authenticationaudit',
            new_name='authenticat_ip_addr_fc46ca_idx',
            old_name='auth_audit_ip_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='dataaccesslog',
            new_name='data_access_user_id_0233e0_idx',
            old_name='data_access_user_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='dataaccesslog',
            new_name='data_access_data_ty_7fecbd_idx',
            old_name='data_access_type_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='dataaccesslog',
            new_name='data_access_platfor_8c2e1c_idx',
            old_name='data_access_platform_timestamp_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='mfadevice',
            unique_together={('user', 'device_id')},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'platform')},
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role', 'facility')},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='auth_user',
        ),
    ]
