# Generated by Django 5.1.2 on 2025-10-17 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='license_expiry',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_expiry',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='primary_role',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='specializations',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_level',
        ),
    ]
