# Generated by Django 5.1.2 on 2025-12-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_default_profile_alter_userprofile_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
