# Generated by Django 5.1.2 on 2025-10-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_license_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_type',
            field=models.CharField(blank=True, choices=[('ghana_card', 'Ghana Card'), ('passport', 'Passport')], max_length=20, null=True),
        ),
    ]
