# Generated by Django 5.1.2 on 2025-10-15 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_guestuser_eventregistration_appointmentrequest_and_more'),
        ('communities', '0003_communityprofile_alter_healthprogram_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityProfile',
        ),
    ]
