# Generated by Django 5.1.2 on 2026-03-14 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_address"),
        ("facilities", "0004_remove_facility_facility_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_assignments",
                to="facilities.facilityprofile",
            ),
        ),
    ]
