# Generated by Django 5.1.2 on 2025-10-15 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_communityprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='preferred_pharmacy',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pharmacyprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='FacilityProfile',
        ),
        migrations.DeleteModel(
            name='PartnerProfile',
        ),
        migrations.DeleteModel(
            name='PatientProfile',
        ),
        migrations.DeleteModel(
            name='PharmacyProfile',
        ),
        migrations.DeleteModel(
            name='ProfessionalProfile',
        ),
    ]
