# Generated by Django 5.1.2 on 2025-10-15 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_partnerprofile_user_and_more'),
        ('communities', '0004_alter_programintervention_referral_facility'),
        ('facilities', '0002_facility_alter_facilityprofile_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='facilities.facility'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_requests', to='facilities.facility'),
        ),
        migrations.AlterField(
            model_name='locumrequest',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locum_requests', to='facilities.facility'),
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
    ]
