# Generated by Django 6.0.4 on 2026-08-02 23:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_address_latitude_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDeliveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('email_type', models.CharField(blank=True, max_length=50)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Delivery Log',
                'verbose_name_plural': 'Email Delivery Logs',
                'db_table': 'email_delivery_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['success', 'created_at'], name='email_deliv_success_50541b_idx'), models.Index(fields=['recipient', 'created_at'], name='email_deliv_recipie_851e3f_idx'), models.Index(fields=['email_type', 'created_at'], name='email_deliv_email_t_4c335c_idx')],
            },
        ),
    ]
