# Generated by Django 5.1.2 on 2025-10-15 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userrole_facility_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='organized_by',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='registrant_guest',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='registrant_user',
        ),
        migrations.RemoveField(
            model_name='guestuser',
            name='converted_to_user',
        ),
        migrations.RemoveField(
            model_name='prescriptionrequest',
            name='requester_guest',
        ),
        migrations.RemoveField(
            model_name='locumrequest',
            name='requester_guest',
        ),
        migrations.RemoveField(
            model_name='locumrequest',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='locumrequest',
            name='matched_professional',
        ),
        migrations.RemoveField(
            model_name='locumrequest',
            name='requester_user',
        ),
        migrations.RemoveField(
            model_name='prescriptionrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='prescriptionrequest',
            name='preferred_pharmacy',
        ),
        migrations.RemoveField(
            model_name='prescriptionrequest',
            name='requester_user',
        ),
        migrations.DeleteModel(
            name='AppointmentRequest',
        ),
        migrations.DeleteModel(
            name='EventRegistration',
        ),
        migrations.DeleteModel(
            name='GuestUser',
        ),
        migrations.DeleteModel(
            name='LocumRequest',
        ),
        migrations.DeleteModel(
            name='PrescriptionRequest',
        ),
    ]
