# Generated by Django 5.1.2 on 2025-10-15 01:47

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ProfessionalProfile',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('practice_type', models.CharField(max_length=100)),
                        ('years_of_experience', models.IntegerField(default=0)),
                        ('education_background', models.JSONField(blank=True, default=list)),
                        ('license_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                        ('license_issuing_body', models.CharField(blank=True, max_length=100, null=True)),
                        ('license_expiry_date', models.DateField(blank=True, null=True)),
                        ('certifications', models.JSONField(blank=True, default=list)),
                        ('availability_schedule', models.JSONField(blank=True, default=dict)),
                        ('preferred_working_hours', models.JSONField(blank=True, default=dict)),
                        ('travel_radius', models.IntegerField(default=0)),
                        ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                        ('currency', models.CharField(default='GHS', max_length=3)),
                        ('specializations', models.JSONField(blank=True, default=list)),
                        ('languages_spoken', models.JSONField(blank=True, default=list)),
                        ('emergency_contact', models.CharField(blank=True, max_length=200, null=True)),
                        ('emergency_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Professional Profile',
                        'verbose_name_plural': 'Professional Profiles',
                        'db_table': 'professional_profiles',
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
