# Generated by Django 5.1.2 on 2025-12-03 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professionals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenceIssueAuthority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Licence Issue Authority",
                "verbose_name_plural": "Licence Issue Authorities",
                "db_table": "licence_issue_authorities",
            },
        ),
        migrations.CreateModel(
            name="Profession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Profession",
                "verbose_name_plural": "Professions",
                "db_table": "professions",
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Specialization",
                "verbose_name_plural": "Specializations",
                "db_table": "specializations",
            },
        ),
        migrations.RenameField(
            model_name="professionalprofile",
            old_name="license_issuing_body",
            new_name="education_status",
        ),
        migrations.RemoveField(
            model_name="professionalprofile",
            name="availability_schedule",
        ),
        migrations.RemoveField(
            model_name="professionalprofile",
            name="certifications",
        ),
        migrations.RemoveField(
            model_name="professionalprofile",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="professionalprofile",
            name="education_background",
        ),
        migrations.RemoveField(
            model_name="professionalprofile",
            name="emergency_contact",
        ),
        migrations.RemoveField(
            model_name="professionalprofile",
            name="emergency_phone",
        ),
        migrations.RemoveField(
            model_name="professionalprofile",
            name="hourly_rate",
        ),
        migrations.RemoveField(
            model_name="professionalprofile",
            name="languages_spoken",
        ),
        migrations.RemoveField(
            model_name="professionalprofile",
            name="practice_type",
        ),
        migrations.RemoveField(
            model_name="professionalprofile",
            name="preferred_working_hours",
        ),
        migrations.RemoveField(
            model_name="professionalprofile",
            name="specializations",
        ),
        migrations.RemoveField(
            model_name="professionalprofile",
            name="travel_radius",
        ),
        migrations.AddField(
            model_name="professionalprofile",
            name="facility_affiliation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="professionalprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="professionalprofile",
            name="license_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="professionalprofile",
            name="years_of_experience",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="EducationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("DIPLOMA", "Diploma"),
                            ("BACHELOR", "Bachelor"),
                            ("MASTER", "Master"),
                            ("DOCTORATE", "Doctorate"),
                            ("PROFESSOR", "Professor"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=100,
                    ),
                ),
                (
                    "education_institution",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "education_institution_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_current_education", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "professional_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_histories",
                        to="professionals.professionalprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education History",
                "verbose_name_plural": "Education Histories",
                "db_table": "education_histories",
            },
        ),
        migrations.AddField(
            model_name="professionalprofile",
            name="license_issuing_authority",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="professional_profiles",
                to="professionals.licenceissueauthority",
            ),
        ),
        migrations.AddField(
            model_name="professionalprofile",
            name="profession",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="professional_profiles",
                to="professionals.profession",
            ),
        ),
        migrations.AddField(
            model_name="professionalprofile",
            name="specialization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="professional_profiles",
                to="professionals.specialization",
            ),
        ),
    ]
