# Generated by Django 5.1.2 on 2025-12-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "professionals",
            "0002_licenceissueauthority_profession_specialization_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="professionalprofile",
            name="education_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IN_SCHOOL", "In School"),
                    ("COMPLETED", "Completed"),
                    ("PRACTICING", "Practicing"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
