# Generated by Django 5.1.2 on 2025-12-05 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
        ("professionals", "0004_availabilityblock_breakperiod_appointment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="client_email",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="client_name",
        ),
        migrations.AddField(
            model_name="appointment",
            name="appointment_type",
            field=models.CharField(
                blank=True,
                choices=[("TELEHEALTH", "Telehealth"), ("IN_PERSON", "In Person")],
                help_text="Type of appointment: Telehealth or In Person",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="patients.patientprofile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                    ("NO_SHOW", "No Show"),
                    ("RESCHEDULED", "Rescheduled"),
                    ("MISSED", "Missed"),
                ],
                default="PENDING",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="telehealth_mode",
            field=models.CharField(
                blank=True,
                choices=[("VIDEO", "Video"), ("CALL", "Call")],
                help_text="Mode for telehealth appointments: Online, Video, or Call",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="visitation_location",
            field=models.CharField(
                blank=True,
                help_text="Location for in-person appointments: Patient visits doctor or doctor visits patient",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="visitation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PATIENT_VISITS_DOCTOR", "Patient Visits Doctor"),
                    ("PROVIDER_VISITS_PATIENT", "Provider Visits Patient"),
                ],
                help_text="Location for in-person appointments: Patient visits doctor or doctor visits patient",
                max_length=50,
                null=True,
            ),
        ),
    ]
