# Generated by Django 5.1.2 on 2025-12-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("professionals", "0006_availability"),
    ]

    operations = [
        migrations.RenameField(
            model_name="professionalprofile",
            old_name="is_active",
            new_name="is_verified",
        ),
    ]
