# Generated by Django 5.1.2 on 2025-12-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professionals", "0007_rename_is_active_professionalprofile_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professionalprofile",
            name="years_of_experience",
            field=models.IntegerField(null=True),
        ),
    ]
