# Generated by Django 6.0.4 on 2026-04-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0008_alter_professionalprofile_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
