# Generated by Django 6.0.4 on 2026-09-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0009_add_is_student_to_professional_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_1h_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_24h_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
