# Generated by Django 5.1.2 on 2025-12-07 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
        ("professionals", "0006_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="patient_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name="PatientAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "health_professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_access",
                        to="professionals.professionalprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_professional_access",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Access",
                "verbose_name_plural": "Patient Access",
                "db_table": "patient_access",
            },
        ),
    ]
