# Generated by Django 5.1.2 on 2025-10-17 00:41

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='home_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='patientprofile',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='patientprofile',
            old_name='updated_at',
            new_name='last_updated',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='current_medications',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='medical_history',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='notification_preferences',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='preferred_consultation_type',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='preferred_language',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='preferred_payment_method',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='preferred_pharmacy',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='work_address',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='other_names',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='patients/profile_pictures/'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
