# Generated by Django 5.1.2 on 2025-12-07 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patientprofile_patient_id_and_more"),
        ("professionals", "0006_availability"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allergy", models.TextField(blank=True, null=True)),
                (
                    "allergy_severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Low"),
                            ("MODERATE", "Moderate"),
                            ("HIGH", "High"),
                            ("VERY_HIGH", "Very High"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergies",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allergy",
                "db_table": "allergies",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="MedicalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("MEDICAL", "Medical"),
                            ("SURGICAL", "Surgical"),
                            ("FAMILY", "Family"),
                            ("PERSONAL", "Personal"),
                            ("PSYCHOLOGICAL", "Psychological"),
                            ("SOCIAL", "Social"),
                            ("ENVIRONMENTAL", "Environmental"),
                            ("GENETIC", "Genetic"),
                            ("ALLERGIC", "Allergic"),
                            ("CHRONIC", "Chronic"),
                            ("OTHER", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("name", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_history",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical History",
                "verbose_name_plural": "Medical History",
                "db_table": "medical_history",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="Visitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitations",
                        to="professionals.professionalprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitations",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visitation",
                "verbose_name_plural": "Visitations",
                "db_table": "visitations",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medication", models.TextField(blank=True, null=True)),
                ("dosage", models.TextField(blank=True, null=True)),
                ("frequency", models.TextField(blank=True, null=True)),
                ("duration", models.TextField(blank=True, null=True)),
                ("instructions", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "visitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="patients.visitation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription",
                "verbose_name_plural": "Prescriptions",
                "db_table": "prescriptions",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="professionals.professionalprofile",
                    ),
                ),
                (
                    "visitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="patients.visitation",
                    ),
                ),
            ],
            options={
                "db_table": "notes",
            },
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "visitation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="patients.visitation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnosis",
                "verbose_name_plural": "Diagnoses",
                "db_table": "diagnoses",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="Vitals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_pressure",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("heart_rate", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "respiratory_rate",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "temperature",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("height", models.CharField(blank=True, max_length=100, null=True)),
                ("weight", models.CharField(blank=True, max_length=100, null=True)),
                ("bmi", models.CharField(blank=True, max_length=100, null=True)),
                ("custom_vitals", models.JSONField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "visitation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to="patients.visitation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vitals",
                "verbose_name_plural": "Vitals",
                "db_table": "vitals",
                "ordering": ["-date_created"],
            },
        ),
    ]
