# Generated by Django 5.1.2 on 2025-12-07 19:00

import uuid
from django.db import migrations, models


def migrate_visitation_id_to_uuid_forward(apps, schema_editor):
    """
    Migrate Visitation id from bigint to UUID.
    Since PostgreSQL can't directly cast bigint to UUID, we need to:
    1. Drop foreign key constraints
    2. Drop the old bigint id column
    3. Add new UUID id column
    4. Update foreign key columns to UUID
    5. Re-add foreign key constraints
    """
    with schema_editor.connection.cursor() as cursor:
        # Enable UUID extension if needed (gen_random_uuid is in pgcrypto)
        cursor.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")

        # Check if table has any data
        cursor.execute("SELECT COUNT(*) FROM visitations;")
        row_count = cursor.fetchone()[0]

        if row_count > 0:
            raise migrations.MigrationError(
                "Cannot migrate Visitation id to UUID when table has existing data. "
                "Please delete all visitations first or manually migrate the data."
            )

        # Drop all constraints and foreign key columns first
        # This ensures we can safely drop the primary key

        # Drop foreign key constraints and columns for all related tables
        cursor.execute(
            """
            ALTER TABLE prescriptions
            DROP CONSTRAINT IF EXISTS prescriptions_visitation_id_fkey CASCADE;
        """
        )
        cursor.execute("ALTER TABLE prescriptions DROP COLUMN IF EXISTS visitation_id;")

        cursor.execute(
            """
            ALTER TABLE notes
            DROP CONSTRAINT IF EXISTS notes_visitation_id_fkey CASCADE;
        """
        )
        cursor.execute("ALTER TABLE notes DROP COLUMN IF EXISTS visitation_id;")

        cursor.execute(
            """
            ALTER TABLE diagnoses
            DROP CONSTRAINT IF EXISTS diagnoses_visitation_id_fkey CASCADE;
        """
        )
        cursor.execute(
            "ALTER TABLE diagnoses DROP CONSTRAINT IF EXISTS diagnoses_visitation_id_key CASCADE;"
        )
        cursor.execute("ALTER TABLE diagnoses DROP COLUMN IF EXISTS visitation_id;")

        cursor.execute(
            """
            ALTER TABLE vitals
            DROP CONSTRAINT IF EXISTS vitals_visitation_id_fkey CASCADE;
        """
        )
        cursor.execute(
            "ALTER TABLE vitals DROP CONSTRAINT IF EXISTS vitals_visitation_id_key CASCADE;"
        )
        cursor.execute("ALTER TABLE vitals DROP COLUMN IF EXISTS visitation_id;")

        # Drop the old primary key constraint and id column from visitations
        cursor.execute(
            "ALTER TABLE visitations DROP CONSTRAINT IF EXISTS visitations_pkey CASCADE;"
        )
        cursor.execute("ALTER TABLE visitations DROP COLUMN IF EXISTS id;")

        # Add new UUID id column with default
        cursor.execute(
            "ALTER TABLE visitations ADD COLUMN id UUID DEFAULT gen_random_uuid() NOT NULL;"
        )

        # Add primary key constraint
        cursor.execute("ALTER TABLE visitations ADD PRIMARY KEY (id);")

        # Re-add foreign key columns with UUID type
        # Prescription and Notes are ForeignKey (nullable allowed)
        cursor.execute("ALTER TABLE prescriptions ADD COLUMN visitation_id UUID;")
        cursor.execute("ALTER TABLE notes ADD COLUMN visitation_id UUID;")

        # Diagnosis and Vitals are OneToOneField (nullable allowed initially, will be set by Django)
        cursor.execute("ALTER TABLE diagnoses ADD COLUMN visitation_id UUID UNIQUE;")
        cursor.execute("ALTER TABLE vitals ADD COLUMN visitation_id UUID UNIQUE;")

        # Re-add foreign key constraints
        cursor.execute(
            """
            ALTER TABLE prescriptions
            ADD CONSTRAINT prescriptions_visitation_id_fkey
            FOREIGN KEY (visitation_id) REFERENCES visitations(id) ON DELETE CASCADE;
        """
        )
        cursor.execute(
            """
            ALTER TABLE notes
            ADD CONSTRAINT notes_visitation_id_fkey
            FOREIGN KEY (visitation_id) REFERENCES visitations(id) ON DELETE CASCADE;
        """
        )
        cursor.execute(
            """
            ALTER TABLE diagnoses
            ADD CONSTRAINT diagnoses_visitation_id_fkey
            FOREIGN KEY (visitation_id) REFERENCES visitations(id) ON DELETE CASCADE;
        """
        )
        cursor.execute(
            """
            ALTER TABLE vitals
            ADD CONSTRAINT vitals_visitation_id_fkey
            FOREIGN KEY (visitation_id) REFERENCES visitations(id) ON DELETE CASCADE;
        """
        )


def migrate_visitation_id_to_uuid_reverse(apps, schema_editor):
    """
    Reverse migration - convert UUID back to bigint
    """
    # This would require converting UUIDs back to bigint, which is not recommended
    # So we'll just make it a no-op for safety
    pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "patients",
            "0003_allergy_medicalhistory_visitation_prescription_notes_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            migrate_visitation_id_to_uuid_forward,
            migrate_visitation_id_to_uuid_reverse,
        ),
        # Update the model state to reflect the UUID field
        migrations.AlterField(
            model_name="visitation",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
