# Generated by Django 5.1.2 on 2025-12-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_alter_visitation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPENED", "Opened"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("ONGOING", "Ongoing"),
                ],
                default="OPENED",
                max_length=100,
            ),
        ),
    ]
