# Generated by Django 5.1.2 on 2026-01-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_visitation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitation",
            name="prescription_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
