# Generated by Django 5.1.2 on 2026-01-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_visitation_prescription_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitation",
            name="prescription_code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
