# Generated by Django 5.1.2 on 2026-03-15 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0005_remove_facilityprofile_facility_and_more"),
        ("patients", "0007_alter_visitation_prescription_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilityPatientAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_access",
                        to="facilities.facilityprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facility_patient_access",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility Patient Access",
                "verbose_name_plural": "Facility Patient Access",
                "db_table": "facility_patient_access",
            },
        ),
    ]
