# Generated by Django 6.0.4 on 2026-04-18 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_add_ward_bed_appointment_labtest_staffinvitation'),
        ('patients', '0008_facilitypatientaccess'),
        ('professionals', '0009_add_is_student_to_professional_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitation',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitations', to='facilities.facilityprofile'),
        ),
        migrations.AddField(
            model_name='visitation',
            name='issued_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitations', to='facilities.facilitystaff'),
        ),
        migrations.AlterField(
            model_name='visitation',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitations', to='professionals.professionalprofile'),
        ),
    ]
