# Generated by Django 6.0.4 on 2026-04-18 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_add_ward_bed_appointment_labtest_staffinvitation'),
        ('professionals', '0009_add_is_student_to_professional_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='professionals.professionalprofile'),
        ),
    ]
